# SimJointq.msg

float64 q_abad_fl      # 关节角度
float64 q_abad_fr      # 关节角度
float64 q_abad_rl      # 关节角度
float64 q_abad_rr      # 关节角度
float64 q_hip_fl       # 关节角度
float64 q_hip_fr       # 关节角度
float64 q_hip_rl       # 关节角度
float64 q_hip_rr       # 关节角度
float64 q_knee_fl      # 关节角度
float64 q_knee_fr      # 关节角度
float64 q_knee_rl      # 关节角度
float64 q_knee_rr      # 关节角度

float64 qd_abad_fl     # 关节速度
float64 qd_abad_fr     # 关节速度
float64 qd_abad_rl     # 关节速度
float64 qd_abad_rr     # 关节速度
float64 qd_hip_fl      # 关节速度
float64 qd_hip_fr      # 关节速度
float64 qd_hip_rl      # 关节速度
float64 qd_hip_rr      # 关节速度
float64 qd_knee_fl     # 关节速度
float64 qd_knee_fr     # 关节速度
float64 qd_knee_rl     # 关节速度
float64 qd_knee_rr     # 关节速度

float64 tau_abad_fl    # 关节力矩
float64 tau_abad_fr    # 关节力矩
float64 tau_abad_rl    # 关节力矩
float64 tau_abad_rr    # 关节力矩
float64 tau_hip_fl     # 关节力矩
float64 tau_hip_fr     # 关节力矩
float64 tau_hip_rl     # 关节力矩
float64 tau_hip_rr     # 关节力矩
float64 tau_knee_fl    # 关节力矩
float64 tau_knee_fr    # 关节力矩
float64 tau_knee_rl    # 关节力矩
float64 tau_knee_rr    # 关节力矩